# https://travis-ci.org

language: cpp

install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes ppa:lttng/daily
  - sudo add-apt-repository ppa:amarburg/opencv3 -y # opencv3 ppa
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopencv3-dev 
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install g++-4.8 -y
  - export CXX="g++-4.8"
script:
  - mkdir release && cd release
  - cmake ..
  - make
